name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.0
    - name: Restore dependencies
      run: dotnet restore apis/poi/poi.sln
    - name: Build
      run: dotnet build --no-restore apis/poi/poi.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal apis/poi/tests/UnitTests/UnitTests.csproj
